name: sabriye
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  analog_clock: ^0.1.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  file_picker: ^4.6.1
  flip_card: ^0.6.0
  flutter: 
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_local_notifications: ^12.0.2
  flutter_rating_bar: ^4.0.1

  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  image_picker: ^0.8.6
  otp_text_field: ^1.1.3
  story_view: ^0.14.0
  url_launcher: ^6.1.7
  webview_flutter: ^2.8.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
   - family: Gastromond
     fonts:
       - asset: assets/fonts/Gastromond-Regular.ttf
         weight: 400
       - asset: assets/fonts/Gastromond-Italic.ttf
   - family: SourceSansPro
     fonts:
       - asset: assets/fonts/SourceSansPro-SemiBold.ttf
      

     
       